### ISSUE TITLE
scrollable region is considerably narrower than dialog region

### ISSUE THREAD

**Issue by ktiedt** [PolymerElements/paper-dialog-scrollable#12]
I have a paper-dialog element that implements paper-dialog-scrollable, I have the dialog CSS set to width: 95% which works great... however the scrollable region "paper-dialog-scrollable #scrollable" element gets constrained programatically to a max-width that appears to be related to the max width of my custom element's parent element (where the custom element defines the dialog)? (The values are similar but not identical).

I have been unable to find CSS to affect this problem... and it severely breaks the flow of the element when the content is shifted so oddly to the left.

**Comment by ktiedt** [comment]
Ok, so of course as soon as I commit to opening an issue, I find a solution but it is not ideal:

```
    --paper-dialog-scrollable: {
      max-width: none !important;
    }
```

Will override the max-width that is being set, but that max-width should never be set in my opinion...

**Comment by miztroh-zz** [comment]
@ktiedt I came across this issue as well.  Good find on the solution.  @arthurevans I don't see that anywhere in the docs.

**Comment by valdrinkoshi** [comment]
Hi @ktiedt, if you set the `width: 95%` to the `paper-dialog`, `paper-dialog-scrollable` will get affected because `#scrollable` is the sizingTarget of the `paper-dialog`. The sizing/positioning then is controlled by the [`iron-fit-behavior`](https://github.com/PolymerElements/iron-fit-behavior)
If you set instead `max-width: 95%`, that does the trick http://jsbin.com/qajuco/1/edit?html,output

@cdata, it seems there's something wrong in the calculations when we set the width/height, WDYT?

**Comment by valdrinkoshi** [comment]
oh, now i get it! `paper-dialog` has `margin: 24px 40px` by default, so if you set `width: 95%` it will sum up to more that 100% when the window size is small.
So@ktiedt if you want to setup the `width: 95%` then also reset the margin to `margin: 24px 0` ;)
http://jsbin.com/qajuco/3/edit?html,output
Closing this
