### ISSUE TITLE
Documentation should make it very clear to set scrollTarget if the paper-dialog-scrollable is not a direct child

### ISSUE THREAD

**Issue by kenchris** [PolymerElements/paper-dialog-scrollable#33]
Potentially make a simple example on how to easily do it and the right time to do so:

Something like:

```
 attached: function() {
        Polymer.dom(this.root).querySelectorAll('paper-dialog-scrollable').forEach((node) => {
            node.dialogElement = this;
        });
}
```

**Comment by jarrodek** [comment]
I agree, I had a problem with it when dialog and scrollable has been created using `document.createElement` instead of template. In my case there was an error assigning dialog to scrollable in `paper-dialog-scrollable` element.

**Comment by valdrinkoshi** [comment]
@kenchris in your example you expect to have multiple `paper-dialog-scrollable`, whereas there can be only one, because `paper-dialog-scrollable` will set the `this.dialogElement.sizingTarget = this`, so that the `paper-dialog-scrollable` will be resized to take the maximum size (`iron-fit-behavior` will do it). Updated the docs accordingly in here #34
