### ISSUE TITLE
paper-dialog-scrollable automatically scrolls to top when the content changes

### ISSUE THREAD

**Issue by kungufli** [PolymerElements/paper-dialog-scrollable#39]
`paper-dialog-scrollable` scrolls automatically to top when the content changes. I think this is an unwanted behavior. Here there is an example: scroll all down and click on the last item (Item 8):
http://jsbin.com/nuyeyotoma/edit?html,output

**Comment by valdrinkoshi** [comment]
Yeah, `iron-collapse` will fire `iron-resize` at the end of the animation, and `iron-overlay-behavior` listens to it and calls `refit` if opened.

I'm not sure this can be solved in `paper-dialog-scrollable` itself, because in this case is the container that causes the `refit`, so it's the container's responsibility to keep track of the scrollTop.
Probably this should be done in `paper-dialog`

In the meantime this should help you :) http://jsbin.com/pipelo/2/edit?html,output

**Comment by valdrinkoshi** [comment]
This issue was moved to PolymerElements/paper-dialog-behavior#73
