### ISSUE TITLE
Automatic scroll to bottom on content addition / append

### ISSUE THREAD

**Issue by turbodonkey** [PolymerElements/paper-dialog-scrollable#52]
I might be doing this wrong, but right now there doesn't appear to be a way to auto scroll to the bottom of the 'scrollable' div upon append'ing new content. For chat programs for example this is table stakes.

Suspect I'm probably using the wrong module or doing something wrong. A search online would suggest that you can do this:

<paper-dialog-scrollable>.$.scrollable.scrollTop = <paper-dialog-scrollable>.$.scrollable.scrollHeight

But this doesn't work for me, there is evidence that .scrollTop is indeed changing, but not to the value of scrollHeight. More interestingly, if I do this manually in the dev tools console, it works!?

**Comment by valdrinkoshi** [comment]
Hi @turbodonkey, I believe that happens because the child is not added yet to the dom (polymer will do it not synchronously for perf reasons). You can either force polymer to perform pending actions with `Polymer.dom.flush()` or wait a tick before updating the scrollTop (e.g. with an `async(callback, 1)`. Here a working example with the flush http://jsbin.com/qejuqij/3/edit?html,output
Hope this helps!

**Comment by turbodonkey** [comment]
Thank you sir, two things I should have done, 1) probably used
stackoverflow for this, my bad. 2) read the docs. I didn't use the same
solution you suggested but you 90% got me on the async war path where the
problem lay.

I found the clue here in dom-repeat template docs, specifically saying that
a .render() needs to be called if you have code which depends on the state.

https://www.polymer-project.org/1.0/docs/api/dom-repeat

Thank you again kind sir!

**Comment by valdrinkoshi** [comment]
glad it helped! Closing the issue ;)
