### ISSUE TITLE
iron-resize event listener not implemented

### ISSUE THREAD

**Issue by balloob** [PolymerElements/paper-dialog-scrollable#9]
An event listener for the `iron-resize` event is [registered](https://github.com/PolymerElements/paper-dialog-scrollable/blob/master/paper-dialog-scrollable.html#L111) but not defined. This raises warnings when an `iron-resize` event is fired.

![screen shot 2015-05-31 at 10 55 40](https://cloud.githubusercontent.com/assets/1444314/7903008/9d2f8208-0783-11e5-9b99-991cf1ffc18a.png)

**Comment by gaarf** [comment]
Am seeing same issue. Warning shows up if `<paper-dialog-scrollable>` contains a resizable (eg `dom-repeat`), and it gets resized while the dialog is open.

**Comment by jfrazzano** [comment]
Am running into a scroll text "clipping" when I set position on the dialog or resize window (causing a default repositioning.). 

Implimemtation, we believed easier issue because of collapses (detail/summary tag and linked text). However, when using just plain string same problem persisted on positioning fixed some top some left. We were going to settle for a center position them same issue occurred when window resized on a right click inspect every in chrome. 

This is likely a behavior issue. Am uncertain, however, as to source. We are working around with a home grown element. This also allows us to WebKit out scroll bars. Any advise welcome. The darned thing was beautiful. We just lost text in our attempted implementation asa data assistant. 

Thanks and good luck. 

Jason

**Comment by jfrazzano** [comment]
Oh, we also saw a "weak map key error" bad map key, no map key, map key undefined I have seen. This was new to me. Seems we can botch something in new ways every day. Hope our fails help. ;-). 

Jason
